---
- hosts: localhost
  become: yes
  ## Ansible is uanble to provision collections/roles before running, requires a seperate ansible-galaxy command..
  # pre_tasks:
  #   - name: Get required roles with ansible galaxy
  #     raw: ansible-galaxy install -r ansible/roles/requirements.yml -p ansible/roles/.tmp

- name: install packages
  import_playbook: ansible/packages.yml

- name: install asdf packages
  import_playbook: ansible/asdf.yml

- name: install yay
  import_playbook: ansible/yay.yml

- name: pull dotfiles
  import_playbook: ansible/dotfiles.yml

- name: configure machine
  import_playbook: ansible/config.yml

- name: configure firefox
  import_playbook: ansible/firefox.yml
