---
- hosts: localhost
  become: yes
  become_user: fredrick

  tasks:
    - name: clone asdf repository
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        version: v0.9.0
        update: no
        accept_hostkey: yes

    - name: add asdf plugins
      shell: . $HOME/.asdf/asdf.sh && asdf plugin add "{{ item }}"
      args:
        executable: /usr/bin/zsh
      with_items:
        - direnv
        - gcloud
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - kubectl
        - stern
        - terraform
        - terraform-docs
        - yq
        - tfsec
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..

    - name: install asdf plugins
      shell: . $HOME/.asdf/asdf.sh && asdf install "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - direnv
        - gcloud
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - kubectl
        - stern
        - terraform
        - terraform-docs
        - yq
        - tfsec

    - name: set global default asdf versions
      shell: . $HOME/.asdf/asdf.sh && asdf global "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - direnv
        - gcloud
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - kubectl
        - stern
        - terraform
        - terraform-docs
        - yq
        - tfsec
