---
- hosts: localhost
  become: yes
  become_user: fredrick

  tasks:
    - name: clone asdf repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "~/.asdf"
        version: v0.8.1
        update: no

    - name: add asdf to bashrc
      blockinfile:
        path: "~/.bashrc"
        block: ". $HOME/.asdf/asdf.sh"
        marker: '# {mark} ANSIBLE MANAGED BLOCK - asdf'

    - name: add asdf plugins
      command: $HOME/.asdf/bin/asdf plugin add "{{ item }}"
      with_items:
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - stern
        - terraform
        - yq
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..

    - name: install asdf plugins
      command: $HOME/.asdf/bin/asdf install "{{ item }}" latest
      with_items:
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - terraform
        - yq

    - name: install asdf stern plugin
      command: $HOME/.asdf/bin/asdf install stern 1.20.0

    - name: set global default asdf versions
      command: $HOME/.asdf/bin/asdf global "{{ item }}" latest
      with_items:
        - github-cli
        - helm
        - istioctl
        - kompose
        - krew
        - terraform
        - yq

    - name: set global default asdf stern version
      command: $HOME/.asdf/bin/asdf global stern 1.20.0

    - name: reshim stern (fix bug)
      command: $HOME/.asdf/bin/asdf reshim stern
