---
- hosts: localhost
  become: yes
  become_user: fredrick

  tasks:
    - name: clone asdf repository
      git:
        repo: 'https://github.com/asdf-vm/asdf.git'
        dest: "~/.asdf"
        version: v0.9.0
        update: no
        accept_hostkey: yes

    - name: add asdf to bashrc
      blockinfile:
        path: "~/.bashrc"
        block: ". $HOME/.asdf/asdf.sh"
        marker: '# {mark} ANSIBLE MANAGED BLOCK - asdf'

    - name: add asdf plugins
      shell: . $HOME/.asdf/asdf.sh && asdf plugin add "{{ item }}"
      args:
        executable: /usr/bin/zsh
      with_items:
        - github-cli
        - helm
        - istioctl
        - kompose
        - gcloud
        - direnv
        - krew
        - stern
        - terraform-docs
        - terraform
        - yq
      register: asdf_add_result
      failed_when:
        - asdf_add_result.rc == 1 or asdf_add_result.rc == 2 and not "'already added' in asdf_add_result.stderr" # Already added plugin should be rc0..

    - name: install asdf plugins
      shell: . $HOME/.asdf/asdf.sh && asdf install "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - github-cli
        - helm
        - istioctl
        - gcloud
        - direnv
        - kompose
        - krew
        - terraform-docs
        - terraform
        - yq

    - name: install asdf stern plugin
      shell: . $HOME/.asdf/asdf.sh && asdf install stern 1.20.0
      args:
        executable: /usr/bin/zsh

    - name: set global default asdf versions
      shell: . $HOME/.asdf/asdf.sh && asdf global "{{ item }}" latest
      args:
        executable: /usr/bin/zsh
      with_items:
        - github-cli
        - helm
        - istioctl
        - direnv
        - kompose
        - krew
        - terraform
        - gcloud
        - terraform-docs
        - yq

    - name: set global default asdf stern version
      shell: . $HOME/.asdf/asdf.sh && asdf global stern 1.20.0
      args:
        executable: /usr/bin/zsh

    - name: reshim stern (fix bug)
      shell: . $HOME/.asdf/asdf.sh && asdf reshim stern
      args:
        executable: /usr/bin/zsh
