---
- hosts: localhost
  become: yes
  tasks:
    - name: reload daemon after installing pipewire
      ansible.builtin.systemd:
        daemon_reload: yes
        scope: user
      become_user: fredrick

    - name: disable pulseaudio
      systemd:
        name: "{{ item }}"
        masked: yes
        state: stopped
        scope: user
      become_user: fredrick
      with_items:
        - pulseaudio.service
        - pulseaudio.socket

    - name: enable pipewire and pulse layer
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
        scope: user
      become_user: fredrick
      with_items:
        - pipewire
        - pipewire-pulse
