---
- hosts: localhost
  become: yes
  vars:
    gpg_pubkey: "7A8CBDC04D43D0DF3116DBB0D79A8F632BA76FC2"

  tasks:
    ##############
    ## Defaults ##
    ##############
    - name: set zsh as default shell
      shell: chsh -s $(which zsh) fredrick

    ######################
    ## Systemd services ##
    ######################

    - name: disable system services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: no
        masked: no
      become_user: root
      with_items:
        - docker.socket
        - docker.service
        - containerd.service

    #############
    ## Flatpak ##
    #############

    - name: flatpak > allow themes folder in home
      command: sudo flatpak override --filesystem=$HOME/.themes
      become_user: fredrick

    - name: flatpak > set dracula as default theme
      command: sudo flatpak override --env=GTK_THEME=Dracula
      become_user: fredrick

    ############
    ## Docker ##
    ############
    - name: add user to docker group
      user: name=fredrick
            groups=docker
            append=yes

    # WARNING: i dont use pass for anything else, bitwarden rules
    - name: deleting existing pass configuration
      ansible.builtin.file:
        path: ~/.password-store/.gpg-id
        state: absent
      become_user: fredrick

    - name: initializing pass with gpg public key
      command: pass init {{ gpg_pubkey }}
      become_user: fredrick

    - name: enable pass backend in docker credsStore
      ansible.builtin.lineinfile:
        path: ~/.docker/config.json
        line: "{ 'credsStore': 'pass' }"
        create: yes
      become_user: fredrick

    ##############
    ## Firewall ##
    ##############

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny

    # - name: Allow ssh, block brute force attempts
    #   community.general.ufw:
    #     rule: limit
    #     port: ssh
    #     proto: tcp

    # - name: Allow all access to tcp port 80
    #   community.general.ufw:
    #     rule: allow
    #     port: '{{ item }}'
    #     proto: tcp
    #   loop:
    #     - '80'
    #     - '443'

    # - name: Allow all access from RFC1918 networks to this host
    #   community.general.ufw:
    #     rule: allow
    #     src: '{{ item }}'
    #   loop:
    #     - 10.0.0.0/24
    #     - 172.17.0.0/16
    #     - 10.244.0.0/16
