---
- hosts: localhost
  become: yes
  tasks:
    ##############
    ## Packages ##
    ##############

    # - name: update & upgrade packages
    #   pacman:
    #     update_cache: yes
    #     upgrade: yes

    - name: install system packages
      pacman:
        state: present
        name:
          - arandr
          - autorandr
          - base
          - base-devel
          - dex
          - dialog
          - dmenu
          - dunst
          - gnome-keyring
          - hsetroot
          - i3-gaps
          - i3blocks
          - i3status-rust
          - light
          - light-locker
          - lightdm
          - lightdm-gtk-greeter
          - lxappearance
          - network-manager-applet
          - nm-connection-editor
          - picom
          - rofi
          - ufw
          - unzip
          - xclip
          - xdg-user-dirs
          - xdg-utils
          - xorg-apps
          - xorg-server
          - xorg-xinit

    - name: install user packages
      pacman:
        state: present
        name:
          - alacritty
          - bat
          - chromium
          - code
          - curl
          - docker
          - docker-compose
          - ethtool
          - firefox
          - flatpak
          - git
          - glow
          - htop
          - libreoffice-still
          - lshw
          - mc
          - mpv
          - neofetch
          - neovim
          - openssh
          - pass
          - pavucontrol
          - peek
          - python-pip
          - thunar
          - tmux
          - transmission-gtk
          - wget
          - xz
          - yubikey-manager
          - zsh

    - name: install laptop packages
      pacman:
        state: present
        name:
          - acpi
          - acpi_call
          - fprintd
          - intel-media-driver
          - intel-ucode
          - linux-firmware
          - linux-firmware-qlogic
          - powertop
          - smartmontools
          - sof-firmware
          - tlp
          - tlp-rdw
          - upower

    - name: install appearance packages
      pacman:
        state: present
        name:
          - arc-gtk-theme
          - noto-fonts
          - papirus-icon-theme
          - terminus-font
          - ttf-dejavu
          - ttf-droid
          - ttf-freefont
          - ttf-jetbrains-mono
          - ttf-liberation
          - ttf-roboto
          - ttf-ubuntu-font-family

    #############
    ## FlatPak ##
    #############

    - name: add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: fredrick

    - name: install flatpak packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
      become_user: fredrick
      with_items:
        - com.discordapp.Discord
        - com.github.wwmm.easyeffects
        - com.gitlab.newsflash
        - com.prusa3d.PrusaSlicer
        - com.slack.Slack
        - com.spotify.Client
        - com.valvesoftware.Steam
        - io.github.hmlendea.geforcenow-electron

    ##############
    ## Binaries ##
    ##############

    # docker-credential-helpers
    - name: check docker-credential-helpers version
      command: /usr/local/bin/docker-credential-pass version
      ignore_errors: yes # First time binary does not exist
      no_log: True # Hide the error log when binary is missing
      register: dch_version
      changed_when: False # Either ok or failed, where is no changed
      failed_when: dch_version.rc == 1 or "0.6.4" not in dch_version.stdout

    - name: download docker-credential-helpers
      get_url:
        url="https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz"
        dest="/tmp/docker-credential-pass-v0.6.4-amd64.tar.gz"
      when: dch_version is failed

    - name: extract docker-credential-pass into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/docker-credential-pass-v0.6.4-amd64.tar.gz
        dest: /usr/local/bin
      when: dch_version is failed

    - name: change perm of "/usr/local/bin/docker-credential-pass", adding "+x"
      file: dest=/usr/local/bin/docker-credential-pass mode=a+x
      when: dch_version is failed

    # ncspot, terminal spotify
    - name: check ncspot version
      command: /usr/local/bin/ncspot --version
      ignore_errors: yes # First time binary does not exist
      no_log: True # Hide the error log when binary is missing
      register: ncspot_version
      changed_when: False # Either ok or failed, where is no changed
      failed_when: ncspot_version.rc == 1 or "0.9.5" not in ncspot_version.stdout

    - name: download ncspot
      get_url:
        url="https://github.com/hrkfdn/ncspot/releases/download/v0.9.5/ncspot-v0.9.5-linux-x86_64.tar.gz"
        dest="/tmp/ncspot-v0.9.5-linux-x86_64.tar.gz"
      when: ncspot_version is failed

    - name: extract ncspot into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/ncspot-v0.9.5-linux-x86_64.tar.gz
        dest: /usr/local/bin
      when: ncspot_version is failed

    - name: change perm of "/usr/local/bin/ncspot", adding "+x"
      file: dest=/usr/local/bin/ncspot mode=a+x
      when: ncspot_version is failed
