---
- hosts: localhost
  become: yes
  tasks:
    ############
    ## Pacman ##
    ############

    - name: update & upgrade packages
      pacman:
        upgrade: yes
        update_cache: yes

    - name: install packages from official
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - acpi_call
        - bat
        - chromium
        - curl
        - docker
        - docker-compose
        - dunst
        - chrony
        - linux-firmware
        - linux-firmware-qlogic
        - ethtool
        - firefox
        - flatpak
        - fprintd
        - intel-ucode
        - intel-media-driver
        - glow
        - htop
        - libreoffice-still
        - mc
        - mpv
        - neofetch
        - neovim
        - pass
        - peek
        - powertop
        - python-pip
        - smartmontools
        - sof-firmware
        - tlp
        - regolith-full
        - tlp-rdw
        - tmux
        - transmission-gtk
        - ufw
        - xclip
        - xz
        - yubikey-manager
        - zsh

    # - name: install apt packages
    #   apt:
    #     update_cache: yes
    #     cache_valid_time: 3600
    #     pkg:
    #     - gnupg-agent
    #     - gpg
    #     - intel-media-va-driver-non-free # Intel Gen 8+ VAAPI
    #     - libpam-fprintd # Fingerprint reader PAM integration

    #############
    ## FlatPak ##
    #############

    - name: add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: fredrick

    - name: install flatpak packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
      become_user: fredrick
      with_items:
        - com.discordapp.Discord
        - com.github.wwmm.easyeffects
        - com.gitlab.newsflash
        - com.prusa3d.PrusaSlicer
        - com.slack.Slack
        - com.spotify.Client
        - com.valvesoftware.Steam
        - io.github.hmlendea.geforcenow-electron

    ##############
    ## Binaries ##
    ##############

    # docker-credential-helpers
    - name: check docker-credential-helpers version
      command: /usr/local/bin/docker-credential-pass version
      ignore_errors: yes # First time binary does not exist
      no_log: True # Hide the error log when binary is missing
      register: dch_version
      changed_when: False # Either ok or failed, where is no changed
      failed_when: dch_version.rc == 1 or "0.6.4" not in dch_version.stdout

    - name: download docker-credential-helpers
      get_url:
        url="https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz"
        dest="/tmp/docker-credential-pass-v0.6.4-amd64.tar.gz"
      when: dch_version is failed

    - name: extract docker-credential-pass into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/docker-credential-pass-v0.6.4-amd64.tar.gz
        dest: /usr/local/bin
      when: dch_version is failed

    - name: change perm of "/usr/local/bin/docker-credential-pass", adding "+x"
      file: dest=/usr/local/bin/docker-credential-pass mode=a+x
      when: dch_version is failed

    # ncspot, terminal spotify
    - name: check ncspot version
      command: /usr/local/bin/ncspot --version
      ignore_errors: yes # First time binary does not exist
      no_log: True # Hide the error log when binary is missing
      register: ncspot_version
      changed_when: False # Either ok or failed, where is no changed
      failed_when: ncspot_version.rc == 1 or "0.9.5" not in ncspot_version.stdout

    - name: download ncspot
      get_url:
        url="https://github.com/hrkfdn/ncspot/releases/download/v0.9.5/ncspot-v0.9.5-linux-x86_64.tar.gz"
        dest="/tmp/ncspot-v0.9.5-linux-x86_64.tar.gz"
      when: ncspot_version is failed

    - name: extract ncspot into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/ncspot-v0.9.5-linux-x86_64.tar.gz
        dest: /usr/local/bin
      when: ncspot_version is failed

    - name: change perm of "/usr/local/bin/ncspot", adding "+x"
      file: dest=/usr/local/bin/ncspot mode=a+x
      when: ncspot_version is failed
