---
- hosts: localhost
  become: true
  tasks:
    ##################
    ## RPM Packages ##
    ##################

    #    - name: Remove packages
    #      dnf:
    #        name:
    #          - rythmbox
    #        state: absent

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Importing RPM keys
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      with_items:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
        - "https://packages.microsoft.com/keys/microsoft.asc"

    ## https://github.com/ansible/ansible/issues/46963
    # - name: Enable the RPM Fusion free repository
    #   dnf:
    #     name:
    #       - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    #       - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    #       - "https://download.docker.com/linux/fedora/docker-ce.repo"
    #     state: present
    #   when: ansible_distribution == 'Fedora'

    - name: Install system packages
      dnf:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose
        state: latest

    - name: Install utility packages
      dnf:
        name:
          - dconf-editor
          - ddcutil
          - fwupd
          - gnome-shell-extension-pop-shell
          - gnome-tweaks
          - powertop
          - xprop
          - golang-github-docker-credential-helpers-devel
        state: latest

    - name: Install user packages
      dnf:
        name:
          - alacritty
          - bat
          - code
          - chromium-freeworld
          - gnome-shell-extension-pop-shell
          - inxi
          - mc
          - mpv
          - neofetch
          - pass
          - peek
          - tmux
          - transmission
          - yubikey-manager
          - zsh
        state: latest

    #############
    ## FlatPak ##
    #############

    - name: add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: fredrick

    - name: install flatpak packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
      become_user: fredrick
      with_items:
        - com.discordapp.Discord
        - com.prusa3d.PrusaSlicer
        - com.github.tchx84.Flatseal
        - org.gnome.Extensions
        - com.github.wwmm.pulseeffects
        - com.jgraph.drawio.desktop
