---
- hosts: localhost
  become: yes
  tasks:
    - name: update & upgrade packages
      pacman:
        upgrade: yes
        update_cache: yes

    - name: install packages from official
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - acpi_call
        - fprintd
        - glfw-wayland
        - gnome-keyring
        - gnome-terminal
        - intel-media-driver
        - intel-ucode
        - linux-firmware
        - linux-firmware-qlogic
        - qt5-wayland
        - sof-firmware
        - sway
        - swaylock
        - waybar
        - wofi
        - xorg-xlsclients
        - xorg-xwayland
        - grim
        - slurp
